Create Table CREATE TABLE `movilesu` (
  `id_movilesu` int(11) NOT NULL,
  `Patente` varchar(25) DEFAULT NULL,
  `Id_Area` int(11) DEFAULT '0',
  `Id_TipoCombustible` int(11) DEFAULT '0',
  `Id_TipoCombustibles` int(11) NOT NULL,
  `Tipo` varchar(50) DEFAULT NULL,
  `Marca` varchar(50) NOT NULL,
  `Modelo` varchar(50) NOT NULL,
  `Interno` varchar(20) NOT NULL,
  `Año` int(4) NOT NULL,
  `Comentarios` varchar(155) NOT NULL,
  `Id_condicion` int(2) NOT NULL,
  `fch_creacion` datetime DEFAULT '0000-00-00 00:00:00',
  `fch_modificacion` datetime DEFAULT '0000-00-00 00:00:00',
  `fch_baja` datetime DEFAULT '0000-00-00 00:00:00',
  UNIQUE KEY `Id_Movil_2` (`id_movilesu`),
  KEY `Id_Area` (`Id_Area`),
  KEY `Id_Movil` (`id_movilesu`),
  KEY `Id_TipoCombustible` (`Id_TipoCombustible`),
  KEY `Patente` (`Patente`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
